// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbXJIlWoyHwGWHTkPZoti-80kSDcmd77I',
    appId: '1:55803376064:web:d225cfd604c7c7e6221825',
    messagingSenderId: '55803376064',
    projectId: 'test-671ce',
    authDomain: 'test-671ce.firebaseapp.com',
    storageBucket: 'test-671ce.firebasestorage.app',
    measurementId: 'G-Y5WZD9FQ6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsN9MX62wClFBqYen-ArCjV82_SO_beeU',
    appId: '1:55803376064:android:e217fbc68d600bde221825',
    messagingSenderId: '55803376064',
    projectId: 'test-671ce',
    storageBucket: 'test-671ce.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgjLcduw_K7wQzrgX-nbZhX3Bzm2DwJIc',
    appId: '1:55803376064:ios:b30eadd28f8920ed221825',
    messagingSenderId: '55803376064',
    projectId: 'test-671ce',
    storageBucket: 'test-671ce.firebasestorage.app',
    iosBundleId: 'com.example.todoFcm',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgjLcduw_K7wQzrgX-nbZhX3Bzm2DwJIc',
    appId: '1:55803376064:ios:b30eadd28f8920ed221825',
    messagingSenderId: '55803376064',
    projectId: 'test-671ce',
    storageBucket: 'test-671ce.firebasestorage.app',
    iosBundleId: 'com.example.todoFcm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbXJIlWoyHwGWHTkPZoti-80kSDcmd77I',
    appId: '1:55803376064:web:bfd3de7f7c4f710a221825',
    messagingSenderId: '55803376064',
    projectId: 'test-671ce',
    authDomain: 'test-671ce.firebaseapp.com',
    storageBucket: 'test-671ce.firebasestorage.app',
    measurementId: 'G-81F69XE03L',
  );
}
